/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_tsingjyujing_geo_jni_NativeS2PointIndex */

#ifndef _Included_com_github_tsingjyujing_geo_jni_NativeS2PointIndex
#define _Included_com_github_tsingjyujing_geo_jni_NativeS2PointIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_tsingjyujing_geo_jni_NativeS2PointIndex
 * Method:    newS2Index
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_tsingjyujing_geo_jni_NativeS2PointIndex_newS2Index
  (JNIEnv *, jclass);

/*
 * Class:     com_github_tsingjyujing_geo_jni_NativeS2PointIndex
 * Method:    deleteS2Index
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_tsingjyujing_geo_jni_NativeS2PointIndex_deleteS2Index
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_tsingjyujing_geo_jni_NativeS2PointIndex
 * Method:    insertPoint
 * Signature: (JDDJ)V
 */
JNIEXPORT void JNICALL Java_com_github_tsingjyujing_geo_jni_NativeS2PointIndex_insertPoint
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jlong);

/*
 * Class:     com_github_tsingjyujing_geo_jni_NativeS2PointIndex
 * Method:    queryPointsNative
 * Signature: (JDDDI)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_github_tsingjyujing_geo_jni_NativeS2PointIndex_queryPointsNative
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
