name: Publish Prod
on:
  create:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish package (Scala 2.12)
        run: mvn -B deploy -Dscala.version.main=2.12 -Dscala.version.sub=12 -Dgeoscala.version=${GITHUB_REF##v}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Publish package (Scala 2.11)
        run: mvn -B deploy -Dscala.version.main=2.11 -Dscala.version.sub=12 -Dgeoscala.version=${GITHUB_REF##v}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}